package net.vulkanmod.vulkan.compat;

import cn.ksmcbrigade.vulkan_core.VKCUnsafeUtils;
import net.vulkanmod.Initializer;
import net.vulkanmod.config.VKNConfig;
import net.vulkanmod.vulkan.VRenderSystem;
import net.vulkanmod.vulkan.transformers.VkInstanceTransformer;
import org.objectweb.asm.ClassWriter;
import org.objectweb.asm.MethodVisitor;
import org.objectweb.asm.Opcodes;

import java.lang.instrument.Instrumentation;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.jar.Attributes;
import java.util.jar.JarEntry;
import java.util.jar.JarOutputStream;
import java.util.jar.Manifest;

/**
 * Installs the Vulkan depth-range correction on {@code org.joml.Matrix4f} at runtime so that
 * EVERY projection matrix Minecraft builds uses Vulkan's [0, 1] clip depth — including ones that
 * entity/model code constructs directly instead of routing through
 * {@code RenderSystem.setProjectionMatrix}. Without this, those directly-built projections keep
 * OpenGL's [-1, 1] depth and their geometry is clipped away, so entities render invisible while
 * terrain (whose projection is always corrected via {@code toVulkanClip} in
 * {@code setProjectionMatrix}) looks fine.
 *
 * <p><b>Surgical-agent approach.</b> We self-attach a tiny, freshly generated in-process Java
 * agent solely to obtain an {@link Instrumentation}, then retransform {@code org.joml.Matrix4f}
 * with a plain ASM transformer ({@link Matrix4fDepthTransformer}). No Mixin is involved and
 * Mixin's IllegalClassLoadError check is never disabled, so this does NOT reintroduce the
 * Cobblemon breakage that caused the external "mr" (MixinRuntime) library to be removed. The
 * agent is our own generated bytecode (no third-party jar): its {@code premain}/{@code agentmain}
 * only stash the {@code Instrumentation} into the {@code "inst"} system property.
 *
 * <p><b>Fail-safe.</b> If the agent cannot attach or the retransform is rejected,
 * {@link VRenderSystem#JOML_DEPTH_FIX_ACTIVE} stays {@code false} and rendering keeps the existing
 * {@code toVulkanClip} behaviour — no regression, the game still launches.
 */
public final class JomlDepthFix {
    private JomlDepthFix() {}

    private static final String AGENT_CLASS = "net.vulkanmod.agent.gen.InstrumentationCaptureAgent";
    private static final String AGENT_INTERNAL = "net/vulkanmod/agent/gen/InstrumentationCaptureAgent";

    private static boolean attempted = false;

    /** Idempotent; safe to call from Vulkan init. Never throws. */
    public static synchronized void install() {
        if (attempted) return;
        attempted = true;
        try {
            Instrumentation inst = acquireInstrumentation();
            if (inst == null) {
                Initializer.LOGGER.warn("[depthFix] no Instrumentation available; entities may be invisible. Keeping toVulkanClip fallback.");
                return;
            }
            Matrix4fDepthTransformer transformer = new Matrix4fDepthTransformer();
            VkInstanceTransformer vkInstanceTransformer = null;
            if(VKNConfig.useVulkanTransformers){
                vkInstanceTransformer = new VkInstanceTransformer();
                inst.addTransformer(vkInstanceTransformer,true);
            }
            inst.addTransformer(transformer, true);
            try {
                inst.retransformClasses(Class.forName("org.joml.Matrix4f"));
                if(VKNConfig.useVulkanTransformers) inst.retransformClasses(Class.forName("org.lwjgl.vulkan.VkInstance"));
            } finally {
                inst.removeTransformer(transformer);
                if(VKNConfig.useVulkanTransformers && vkInstanceTransformer!=null) inst.removeTransformer(vkInstanceTransformer);
            }
            if (transformer.applied) {
                VRenderSystem.JOML_DEPTH_FIX_ACTIVE = true;
                Initializer.LOGGER.info("[depthFix] org.joml.Matrix4f retransformed to Vulkan depth (zZeroToOne); entities will render, toVulkanClip bypassed.");
            } else {
                Initializer.LOGGER.warn("[depthFix] Matrix4f retransform matched no methods; keeping toVulkanClip fallback.");
            }
        } catch (Throwable t) {
            VRenderSystem.JOML_DEPTH_FIX_ACTIVE = false;
            Initializer.LOGGER.error("[depthFix] failed to install JOML depth fix; keeping toVulkanClip fallback (entities may be invisible).", t);
        }
    }

    private static Instrumentation acquireInstrumentation() throws Exception {
        Object existing = System.getProperties().get("inst");
        if (existing instanceof Instrumentation) return (Instrumentation) existing;

        Path agentJar = buildAgentJar();
        // VKCUnsafeUtils.loadAgent self-attaches to this JVM and loads the agent, whose
        // premain/agentmain publishes the Instrumentation to the "inst" system property.
        VKCUnsafeUtils.loadAgent(agentJar.toAbsolutePath().toString());

        Object captured = System.getProperties().get("inst");
        return (captured instanceof Instrumentation) ? (Instrumentation) captured : null;
    }

    /** Writes a minimal, self-generated agent jar to a temp file and returns its path. */
    private static Path buildAgentJar() throws Exception {
        byte[] clazz = agentClassBytes();

        Manifest mf = new Manifest();
        Attributes a = mf.getMainAttributes();
        a.put(Attributes.Name.MANIFEST_VERSION, "1.0");
        a.putValue("Agent-Class", AGENT_CLASS);
        a.putValue("Premain-Class", AGENT_CLASS);
        a.putValue("Can-Retransform-Classes", "true");
        a.putValue("Can-Redefine-Classes", "true");

        Path jar = Files.createTempFile("vulkanmod-inst-agent", ".jar");
        jar.toFile().deleteOnExit();
        try (JarOutputStream jos = new JarOutputStream(Files.newOutputStream(jar), mf)) {
            jos.putNextEntry(new JarEntry(AGENT_INTERNAL + ".class"));
            jos.write(clazz);
            jos.closeEntry();
        }
        return jar;
    }

    /**
     * Generates the agent class:
     * <pre>
     * public class InstrumentationCaptureAgent {
     *     public static void premain(String a, Instrumentation i)   { System.getProperties().put("inst", i); }
     *     public static void agentmain(String a, Instrumentation i) { System.getProperties().put("inst", i); }
     * }
     * </pre>
     */
    private static byte[] agentClassBytes() {
        ClassWriter cw = new ClassWriter(0);
        cw.visit(Opcodes.V17, Opcodes.ACC_PUBLIC | Opcodes.ACC_SUPER, AGENT_INTERNAL, null, "java/lang/Object", null);

        MethodVisitor ctor = cw.visitMethod(Opcodes.ACC_PUBLIC, "<init>", "()V", null, null);
        ctor.visitCode();
        ctor.visitVarInsn(Opcodes.ALOAD, 0);
        ctor.visitMethodInsn(Opcodes.INVOKESPECIAL, "java/lang/Object", "<init>", "()V", false);
        ctor.visitInsn(Opcodes.RETURN);
        ctor.visitMaxs(1, 1);
        ctor.visitEnd();

        for (String method : new String[]{"premain", "agentmain"}) {
            MethodVisitor mv = cw.visitMethod(Opcodes.ACC_PUBLIC | Opcodes.ACC_STATIC, method,
                    "(Ljava/lang/String;Ljava/lang/instrument/Instrumentation;)V", null, null);
            mv.visitCode();
            mv.visitMethodInsn(Opcodes.INVOKESTATIC, "java/lang/System", "getProperties", "()Ljava/util/Properties;", false);
            mv.visitLdcInsn("inst");
            mv.visitVarInsn(Opcodes.ALOAD, 1);
            mv.visitMethodInsn(Opcodes.INVOKEVIRTUAL, "java/util/Properties", "put",
                    "(Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object;", false);
            mv.visitInsn(Opcodes.POP);
            mv.visitInsn(Opcodes.RETURN);
            mv.visitMaxs(3, 2);
            mv.visitEnd();
        }

        cw.visitEnd();
        return cw.toByteArray();
    }
}
