plugins {
    id 'dev.architectury.loom' version '1.11-SNAPSHOT'
    id 'maven-publish'
}

group = project.maven_group
version = project.mod_version

base {
    archivesName = project.archives_name
}

repositories {
    // Add NeoForged repository.
    maven {
        name = 'NeoForged'
        url = 'https://maven.neoforged.net/releases'
    }
    maven {
        name = "Modrinth"
        url = "https://api.modrinth.com/maven"
    }

    maven { url = "https://maven.createmod.net" } // Ponder, Flywheel

    maven { url = "https://maven.ithundxr.dev/snapshots" } // Registrate
    maven { url = "https://maven.blamejared.com" } // JEI, Vazkii's Mods
    maven { url = "https://maven.theillusivec4.top/" } // Curios API
    maven { url = "https://maven.squiddev.cc" } // CC: Tweaked
    maven { url = "https://www.cursemaven.com" }
    maven { url = "https://api.modrinth.com/maven" }
    maven { url = "https://maven.ftb.dev/releases" } // FTB Mods
    maven { url = "https://maven.architectury.dev" } // Arch API
    // NeoForge config api port, needed by ponder
    maven { url = "https://raw.githubusercontent.com/Fuzss/modresources/main/maven" }
    maven {
        url = "https://jm.gserv.me/repository/maven-public" // JourneyMap
        content {
            includeGroup "info.journeymap"
            includeGroup "mysticdrew"
        }
    }
    maven { url "https://chocolateminecraft.com/maven" } // Xaero
    maven {
        name = "Sinytra"
        url = uri("https://maven.su5ed.dev/releases")
    }
}

loom {
    silentMojangMappingsLicense()
    accessWidenerPath = file("src/main/resources/vulkanmod.accesswidener")
    neoForge {
        accessWidenerPath = file("src/main/resources/vulkanmod.accesswidener")
        accessTransformers = files("src/main/resources/META-INF/accesstransformer.cfg")
    }
}

project.ext.lwjglVersion = "3.3.3"
project.ext.jomlVersion = "1.10.4"
project.ext.winNatives = "natives-windows"
project.ext.linuxNatives = "natives-linux"
project.ext.macosNatives = "natives-macos"
project.ext.macosArmNatives = "natives-macos-arm64"

dependencies {
    minecraft "net.minecraft:minecraft:$project.minecraft_version"
    mappings loom.officialMojangMappings()
    neoForge "net.neoforged:neoforge:$project.neoforge_version"

    implementation("org.lwjgl:lwjgl-vulkan:$lwjglVersion")

	ext.includeNatives = { name ->
		implementation("$name:$lwjglVersion")
		implementation("$name:$lwjglVersion:$winNatives")
		runtimeOnly("$name:$lwjglVersion:$linuxNatives")
		runtimeOnly("$name:$lwjglVersion:$macosNatives")
		runtimeOnly("$name:$lwjglVersion:$macosArmNatives")
	}

	includeNatives("org.lwjgl:lwjgl-vma")
	includeNatives("org.lwjgl:lwjgl-shaderc")

	//MoltenVK
	implementation("org.lwjgl:lwjgl-vulkan:$lwjglVersion:$macosNatives")
	implementation("org.lwjgl:lwjgl-vulkan:$lwjglVersion:$macosArmNatives")

    include(modImplementation("maven.modrinth:mixinruntime:1.0.2-mc1.21"))

    //combat create

//    modApi("com.tterrag.registrate:Registrate:$registrate_version")
    modImplementation("dev.engine-room.flywheel:flywheel-neoforge-api-1.21.1:1.0.6")
    //modImplementation("net.createmod.ponder:ponder-neoforge:1.0.82+mc1.21.1")
   // modImplementation("maven.modrinth:create:6.0.10+mc1.21.1")

    //forgified fabric api is required

    //fabric loader
    compileOnly("org.sinytra:forgified-fabric-loader:$versionForgifiedFabricLoader")
    runtimeOnly("org.sinytra:forgified-fabric-loader:$versionForgifiedFabricLoader:full")

    //fabric api
    modImplementation "org.sinytra.forgified-fabric-api:fabric-api-base:0.4.42+d1308ded19"
    modImplementation "org.sinytra.forgified-fabric-api:fabric-resource-loader-v0:1.3.1+4ea8954419"
    modImplementation "org.sinytra.forgified-fabric-api:fabric-rendering-fluids-v1:3.1.6+a51883b219"
    modImplementation "org.sinytra.forgified-fabric-api:fabric-renderer-api-v1:3.4.1+9125b6dc19"
    modImplementation "org.sinytra.forgified-fabric-api:fabric-rendering-v1:5.1.0+1a09bd5a19"
    modImplementation "org.sinytra.forgified-fabric-api:fabric-rendering-data-attachment-v1:0.3.49+73761d2e19"
    modImplementation "org.sinytra.forgified-fabric-api:fabric-block-view-api-v2:1.0.11+e9036fd419"
}

processResources {
    inputs.property 'version', project.version

    filesMatching('META-INF/neoforge.mods.toml') {
        expand version: inputs.properties.version
    }
}

java {
    // Loom will automatically attach sourcesJar to a RemapSourcesJar task and to the "build" task
    // if it is present.
    // If you remove this line, sources will not be generated.
    withSourcesJar()

    sourceCompatibility = JavaVersion.VERSION_21
    targetCompatibility = JavaVersion.VERSION_21
}

tasks.withType(JavaCompile).configureEach {
    it.options.release = 21
}

// Configure Maven publishing.
publishing {
    publications {
        mavenJava(MavenPublication) {
            from components.java
        }
    }

    // See https://docs.gradle.org/current/userguide/publishing_maven.html for information on how to set up publishing.
    repositories {
        // Add repositories to publish to here.
        // Notice: This block does NOT have the same function as the block in the top level.
        // The repositories here will be used for publishing your artifact, not for
        // retrieving dependencies.
    }
}
