modLoader = "javafml"
loaderVersion = "[4,)"
#issueTrackerURL = ""
license = "LGPL-3.0"

[[mods]]
modId = "vulkanmod"
version = "${version}"
displayName = "NeoVulkanMod"
authors = "Collateral,commonplace(KSmc_brigade)"
description = '''
VulkanMod in NeoForge 1.20
We got the VulkanModNeoForge before GTA 6.
'''
#logoFile = ""

[[dependencies.vulkanmod]]
modId = "forge"
mandatory=true
type = "required"
versionRange = "[47.0,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.vulkanmod]]
modId = "minecraft"
mandatory=true
type = "required"
versionRange = "[1.20,1.20.4)"
ordering = "NONE"
side = "BOTH"
[[dependencies.vulkanmod]]
modId = "fabric_api_base"
mandatory=true
type = "required"
versionRange = "[0,)"
ordering = "NONE"
side = "BOTH"
